"""Configuration dataclasses for the differentiable smFRET likelihood.

All quantities use the *simulator* unit system so that data generated by
``smFRET_sbi`` can be fed in with no rescaling:

    time      : milliseconds  (ms)          -- inter-photon times, T
    distance  : nanometres    (nm)          -- x, R0, grid
    diffusion : nm^2 / ms                   -- physical D (see logD note below)
    rates     : kHz  (= 1/ms)               -- kD, backgrounds, emission mu

Diffusion transform: ``D`` is a *physical* value in nm^2/ms.  The likelihood
optimiser works in **natural**-log space (``D = exp(logD)``, see ``infer.py``),
matching SPEC section 7.4 (``D = e^{(.)}``).  The ``smFRET_sbi`` simulator
separately parameterises its input as **base-10** ``log10(D)``
(``simulator.py``: ``Dx = 10**theta[0]``); the two conventions are distinct and
must not be conflated.

See ``SPEC`` sections 3 and 5.  Everything downstream assumes float64 in the
likelihood path (``config.DTYPE``).
"""

from __future__ import annotations

from dataclasses import dataclass

import torch

# The likelihood is designed for double precision: the eigendecomposition +
# log-normalizers need float64 (SPEC section 8).  Keep this the single source of
# truth for the intended dtype.
DTYPE = torch.float64


def use_float64() -> None:
    """Set torch's global default dtype to float64 (the dtype the likelihood is
    designed for).

    Importing ``diff_fret_likelihood`` does **not** mutate global torch state;
    call this once (before building configs / running a fit) if you want tensors
    created without an explicit dtype to default to float64. The test suite sets
    this in ``tests/conftest.py``.
    """
    torch.set_default_dtype(DTYPE)


@dataclass
class GridConfig:
    """Spatial grid on which the Smoluchowski generator lives.

    The grid must cover the data-visited region with margin; see
    ``tests/test_grid_convergence.py``.
    """

    x_min: float
    x_max: float
    n_grid: int = 160

    def build(self, device="cpu") -> torch.Tensor:
        """Return the grid ``xi`` of shape ``[n_grid]`` (float64)."""
        return torch.linspace(
            self.x_min, self.x_max, self.n_grid, dtype=DTYPE, device=device
        )

    @property
    def dx(self) -> float:
        return (self.x_max - self.x_min) / (self.n_grid - 1)


@dataclass
class PotentialConfig:
    """Natural-cubic potential-knot spline ``u_theta(x)`` (units of k_B T).

    The free parameters are the ``n_knots`` knot *heights*, so ``u`` is linear in
    them -- see ``potential.SplinePotential`` for why that linearity matters to the
    Fisher/CRB and to the gauge anchor.  ``build_potential`` fills ``x_center`` /
    ``x_scale`` from the grid extent when they are left ``None``, which places the
    knots uniformly over ``[x_center - x_scale, x_center + x_scale]``.

    (Up to 0.2.0 a ``kind`` field selected between this and an MLP parameterisation.
    The MLP is gone and so is the field; callers that passed ``kind="spline"`` simply
    drop the argument.)
    """

    # --- knot window (defaults to the grid extent, via build_potential) ---
    x_center: float | None = None
    x_scale: float | None = None
    n_knots: int = 9


@dataclass
class PhysicsConstants:
    """Fixed calibration constants (NOT optimised).

    Crosstalk convention matches ``smFRET_sbi`` / ``diff_fret_photon``:
        green channel sees   C_gg * rD + C_rg * rA
        red   channel sees   C_gr * rD + C_rr * rA
    with rD = kD (1-E), rA = kD E, and photon conservation
        C_gg = 1 - C_gr,   C_rr = 1 - C_rg.
    """

    R0: float = 6.0
    C_gg: float = 0.90
    C_gr: float = 0.10
    C_rg: float = 0.05
    C_rr: float = 0.95

    def crosstalk_tensor(self, device="cpu") -> torch.Tensor:
        """2x2 crosstalk ``C`` with rows=source(D,A), cols=channel(G,R).

        ``C[0,0]=C_gg`` (D->G), ``C[1,0]=C_rg`` (A->G),
        ``C[0,1]=C_gr`` (D->R), ``C[1,1]=C_rr`` (A->R).
        """
        return torch.tensor(
            [[self.C_gg, self.C_gr], [self.C_rg, self.C_rr]],
            dtype=DTYPE,
            device=device,
        )


@dataclass
class PriorConfig:
    """Priors / regularisers (SPEC section 9).

    ``curvature_weight`` multiplies ``objective.curvature_penalty_spline``: the squared
    (or, with ``curvature_norm="l1"``, absolute) second difference of the KNOT HEIGHTS,
    summed over interior knots.  It is a bare sum, NOT normalised by knot spacing, so a
    weight is only meaningful at the ``n_knots`` it was selected at (equivalents scale
    roughly as ``1/(n_knots-1)``); select it truth-free by held-out likelihood rather
    than transplanting one.  Grid-independent by construction -- it never touches the
    fine grid, only the knots that carry the degrees of freedom.

    Two terms, and only two: the curvature roughness above and the background Gamma
    prior below.  Each is toggled by a sentinel (weight ``0`` or ``None``).
    ``PriorConfig()`` is prior-free by default (``curvature_weight=0.0``, both terms
    off) -- equivalent to pure MLE; switch on the terms you want, or pass ``prior=None``
    to ``fit`` / ``neg_log_posterior`` (or use ``PriorConfig.none()`` when an instance is
    required) for an explicit MLE.  ``active_terms()`` / ``describe()`` report which
    terms are on.

    Note the curvature prior is the *improper* thin-plate limit: it penalises roughness
    only, leaving the constant and linear directions of ``U`` unpenalised.  The constant
    is pure gauge and is handled separately (``objective.gauge_penalty``), but nothing
    here makes the landscape posterior proper.  A GP prior that did was removed in 0.3.0
    along with the ``logD`` prior and ``l2_weight`` -- none had ever been switched on in
    an analysis; see CHANGELOG.md.
    """

    # --- landscape roughness (improper thin-plate; scaled by this weight) ---
    curvature_weight: float = 0.0  # rho * integral (u'')^2 dx  (grid-invariant units)
    # "l2" (default, Gaussian: sum d2^2) | "l1" (Laplace / total-variation: sum |d2|).
    # L1 is edge-preserving: it keeps a few large curvature features (barriers,
    # intermediates) while suppressing many small wiggles. SplinePotential only.
    # The two norms live on DIFFERENT scales -- curvature_weight does not carry over.
    curvature_norm: str = "l2"
    # --- Gamma prior on the backgrounds, from an independent calibration ---
    # Everything in kHz, the same units as the rates themselves: `bg_c_mean` is what a
    # blank / donor-only window measures and `bg_c_sd` is that measurement's error bar.
    # Each channel is gated by its own mean (`None` -> that channel is unconstrained) and
    # then REQUIRES its sd -- a mean without an error bar is not a measurement.
    # Per channel, not shared, because a calibration reports one error bar per detector;
    # set them equal if yours does not distinguish.  See objective.bg_penalty for the
    # form, and why a counted background is a Gamma rather than a Gaussian.
    bg_g_mean: float | None = None
    bg_g_sd: float | None = None
    bg_r_mean: float | None = None
    bg_r_sd: float | None = None

    def __post_init__(self):
        if self.curvature_weight < 0:
            raise ValueError(
                f"curvature_weight must be >= 0, got {self.curvature_weight}"
            )
        for _c in ("g", "r"):
            _m = getattr(self, f"bg_{_c}_mean")
            _s = getattr(self, f"bg_{_c}_sd")
            if _m is None:
                continue
            if _m <= 0:
                raise ValueError(f"bg_{_c}_mean is a rate in kHz and must be > 0, got {_m}")
            if _s is None:
                raise ValueError(
                    f"bg_{_c}_mean={_m} was given without bg_{_c}_sd. A calibrated "
                    f"background needs its error bar (kHz); a mean alone is not a "
                    f"measurement."
                )
            if _s <= 0:
                raise ValueError(f"bg_{_c}_sd is a rate in kHz and must be > 0, got {_s}")

    @classmethod
    def none(cls) -> "PriorConfig":
        """A fully prior-free config (pure MLE): every term disabled.

        Numerically equivalent to passing ``prior=None`` to ``fit`` /
        ``neg_log_posterior``; provided for callers that need a ``PriorConfig``
        instance rather than ``None``.
        """
        return cls()  # every field default is already the prior-off sentinel

    def active_terms(self) -> list[str]:
        """Names of the prior terms currently switched on (empty -> pure MLE)."""
        terms: list[str] = []
        if self.curvature_weight:
            terms.append("curvature")
        if self.bg_g_mean is not None or self.bg_r_mean is not None:
            terms.append("bg")
        return terms

    def describe(self) -> str:
        """Human-readable summary of which priors are active."""
        active = self.active_terms()
        return "MLE (no prior)" if not active else "MAP prior: " + ", ".join(active)


@dataclass
class OptimConfig:
    """Guarded LBFGS with plateau stopping.

    Each step is ONE quasi-Newton step (``max_iter=1``; the L-BFGS curvature
    history persists across calls), so the non-finite guard and the plateau stop
    act between every step.  The fit stops once the best loss has not
    improved by more than ``stop_min_delta`` nats within ``stop_patience`` steps;
    any non-finite loss/param restores the best snapshot and stops.  See
    ``infer._lbfgs_fit``.
    """

    steps: int = 600            # hard cap; the plateau stop usually fires first
    lbfgs_lr: float = 1.0       # 1.0 is the measured-safe step; 0.1 diverged late
    history_size: int = 100
    stop_patience: int = 50     # stop when best loss unimproved for this many steps...
    stop_min_delta: float = 0.1  # ...by more than this many nats
    log_every: int = 25
    compile: bool = False
    compile_mode: str = "default"
    propagate_dtype: "torch.dtype | None" = None
