"""Configuration dataclasses for the differentiable smFRET likelihood.

All quantities use the *simulator* unit system so that data generated by
``smFRET_sbi`` can be fed in with no rescaling:

    time      : milliseconds  (ms)          -- inter-photon times, T
    distance  : nanometres    (nm)          -- x, R0, grid
    diffusion : nm^2 / ms                   -- physical D (see logD note below)
    rates     : kHz  (= 1/ms)               -- kD, backgrounds, emission mu

Diffusion transform: ``D`` is a *physical* value in nm^2/ms.  The likelihood
optimiser works in **natural**-log space (``D = exp(logD)``, see ``infer.py``),
matching SPEC section 7.4 (``D = e^{(.)}``).  The ``smFRET_sbi`` simulator
separately parameterises its input as **base-10** ``log10(D)``
(``simulator.py``: ``Dx = 10**theta[0]``); the two conventions are distinct and
must not be conflated.

See ``SPEC`` sections 3 and 5.  Everything downstream assumes float64 in the
likelihood path (``config.DTYPE``).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence

import torch

# Non-negotiable: the eigendecomposition + log-normalizers need float64
# (SPEC section 8).  Keep this the single source of truth.
DTYPE = torch.float64


@dataclass
class GridConfig:
    """Spatial grid on which the Smoluchowski generator lives.

    The grid must cover the data-visited region with margin; see
    ``tests/test_grid_convergence.py``.
    """

    x_min: float
    x_max: float
    n_grid: int = 160

    def build(self, device="cpu") -> torch.Tensor:
        """Return the grid ``xi`` of shape ``[n_grid]`` (float64)."""
        return torch.linspace(
            self.x_min, self.x_max, self.n_grid, dtype=DTYPE, device=device
        )

    @property
    def dx(self) -> float:
        return (self.x_max - self.x_min) / (self.n_grid - 1)


@dataclass
class PotentialConfig:
    """MLP potential ``u_theta(x)`` (units of k_B T).

    ``kind='mlp'`` -> smooth-activation MLP (SPEC primary).
    ``kind='spline'`` -> natural-cubic potential-knot spline (linear in the
    parameters; a stable low-dimensional alternative used for cross-checks).
    """

    kind: str = "mlp"
    # --- shared: input normalisation window (defaults to grid extent) ---
    x_center: float | None = None
    x_scale: float | None = None
    # --- mlp ---
    hidden: Sequence[int] = (32, 32)
    activation: str = "silu"  # smooth; never relu
    # --- spline ---
    n_knots: int = 9


@dataclass
class PhysicsConstants:
    """Fixed calibration constants (NOT optimised).

    Crosstalk convention matches ``smFRET_sbi`` / ``diff_fret_photon``:
        green channel sees   C_gg * rD + C_rg * rA
        red   channel sees   C_gr * rD + C_rr * rA
    with rD = kD (1-E), rA = kD E, and photon conservation
        C_gg = 1 - C_gr,   C_rr = 1 - C_rg.
    """

    R0: float = 6.0
    C_gg: float = 0.90
    C_gr: float = 0.10
    C_rg: float = 0.05
    C_rr: float = 0.95

    def crosstalk_tensor(self, device="cpu") -> torch.Tensor:
        """2x2 crosstalk ``C`` with rows=source(D,A), cols=channel(G,R).

        ``C[0,0]=C_gg`` (D->G), ``C[1,0]=C_rg`` (A->G),
        ``C[0,1]=C_gr`` (D->R), ``C[1,1]=C_rr`` (A->R).
        """
        return torch.tensor(
            [[self.C_gg, self.C_gr], [self.C_rg, self.C_rr]],
            dtype=DTYPE,
            device=device,
        )


@dataclass
class PriorConfig:
    """Priors / regularisers (SPEC section 9).

    ``curvature_weight`` multiplies the GRID-INVARIANT roughness penalty
    ``~= integral (u'')^2 dx`` (see ``objective.curvature_penalty``).  Units changed
    from the legacy ``sum d2^2`` form: the natural range here is O(1e-2 .. 1e-1) and is
    swept/selected in the benchmark's Phase A.  (Legacy weight ``w_old`` on grid spacing
    ``dx`` maps to ``w_new = w_old * dx**3``.)  The benchmark stamps
    ``curvature_units="integral_u2pp_dx"`` in every result row so old/new runs never mix.

    GP prior (``gp_*``): a PROPER stationary-kernel Gaussian-process prior over the
    landscape ``U(x)`` (see ``objective.gp_penalty``).  Where ``curvature_penalty`` is
    the *improper* thin-plate limit (only roughness; constant+linear unpenalised), the
    GP prior adds a finite amplitude ``gp_sigma`` (kT) and correlation length
    ``gp_lengthscale`` (nm), making the landscape posterior proper -- essential for
    HMC sampling (see ``sample.py``).  ``gp_sigma=None`` disables it (default), so the
    objective is byte-for-byte unchanged unless the GP is explicitly switched on.
    Recommendation: use the GP as the SINGLE shape prior (``curvature_weight=0``);
    don't stack two strong smoothness priors.
    """

    curvature_weight: float = 0.05  # rho * integral (u'')^2 dx  (grid-invariant units)
    logD_mean: float | None = None  # weak Gaussian prior on log D (None -> off)
    logD_std: float = 1.0
    l2_weight: float = 0.0  # optional weak L2 on potential params
    # --- proper GP prior over U(x) (None sigma -> OFF; fully backward-compatible) ---
    gp_sigma: float | None = None      # marginal SD (kT); None DISABLES the GP prior
    gp_lengthscale: float = 1.0        # correlation length (nm)
    gp_kernel: str = "matern52"        # "rbf" | "matern32" | "matern52"
    gp_n_ctrl: int = 16                # control points; clamped to [4, n_grid]
    gp_mean: "torch.Tensor | None" = None  # [G] on the grid; interp'd to x_ctrl; None -> 0
    gp_jitter: float = 1e-6            # relative to the correlation matrix (FIXED)

    def __post_init__(self):
        if self.gp_sigma is not None:
            if self.gp_sigma <= 0:
                raise ValueError(f"gp_sigma must be > 0, got {self.gp_sigma}")
            if self.gp_lengthscale <= 0:
                raise ValueError(
                    f"gp_lengthscale must be > 0, got {self.gp_lengthscale}"
                )
            if self.gp_kernel not in ("rbf", "matern32", "matern52"):
                raise ValueError(
                    f"gp_kernel must be rbf|matern32|matern52, got {self.gp_kernel!r}"
                )


@dataclass
class OptimConfig:
    """Adam warmup -> LBFGS polish (SPEC section 7.6)."""

    adam_steps: int = 10
    adam_lr: float = 0.02
    lbfgs_steps: int = 0
    lbfgs_lr: float = 0.5
    grad_clip: float = 10.0
    log_every: int = 25
    # torch.compile the photon recursion (fusion win, numerically transparent --
    # see tests/test_compile.py).  ``compile=False`` -> eager.  Default mode is
    # inductor "default" (fast, robust ~1.1x); "reduce-overhead" (CUDA-graphs)
    # gives negligible extra here -- the recursion is fp64-compute-bound, not
    # launch-bound -- and compiles very slowly over long photon streams.
    compile: bool = False
    compile_mode: str = "default"
    # Mixed-precision recursion (fp32 matmuls, fp64 log-normaliser) -- large GPU
    # win where fp64 is throttled; accuracy-gated (tests/test_fp32.py). None ->
    # full float64.  Set to ``torch.float32`` to enable.
    propagate_dtype: "torch.dtype | None" = None
